config/routes.rb
Homebase::Application.routes.draw do
 root :to => "chats#index"
    resources :chats
   match '/party/:id', :to => "chats#party", :as => :party, :via => :get
end

app/models/chat.rb
class Chat < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
require "opentok"

def index
	@chats = Chat.order("created_at DESC")
end

def new
	@chat = Chat.new
end

def create
	session = opentok.create_session :media_mode => :relayed
	token = session.generate_token
end

def show
	@chat = Chat.find(params[:id])
end

private
	def chat_params
    	params.require(:chat).permit(:sessionId,:user_id,:token)
  	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/views/chats/index.html.erb
<div id="newRoom">
	<fieldset>
		<legend>Start a new party chat</legend>
		<%= button_to 'Start Chat', new_chat_path %>
	</fieldset>
</div>

	<fieldset>
		<legend>Existing party chats</legend>
		<table cellpadding="2" cellspacing="5">
			<tr>
				<th>ID</th>
				<th>Started</th>
			</tr>

				<% @chats.each do |chat| %>
			<tr>
				<td align="center" width="300px"><a href="/party/<%= chat.id %>"><%= chat.id %></a></td>
				<td><%= chat.created_at %></td>
			</tr>
		<% end %>

		<%= @numbers.all %>

		</table>
	</fieldset>

app/views/chats/new.html.erb
		<%= form_for(@chat) do |f| %>
			<%= f.hidden_field sessionId: sessionId %>
			<%= f.hidden_field token: token %>
		<%= f.submit %>
		<% end %>

app/views/chats/party.html.erb
 <div id="myPublisherDiv"></div>
        <script type="text/javascript">
          // Initialize API key, session, and token...
          // Think of a session as a room, and a token as the key to get in to the room
          // Sessions and tokens are generated on your server and passed down to the client
          var apiKey = "44745342";
          var sessionId = <%= @chat.sessionId %>;
          var token = <%= @chat.token %>;

          // Initialize session, set up event listeners, and connect
          var session = TB.initSession(sessionId);
          session.addEventListener('sessionConnected', sessionConnectedHandler);
          session.connect(apiKey, token);
          
          function sessionConnectedHandler(event) {
            var publisher = TB.initPublisher(apiKey, 'myPublisherDiv');
            session.publish(publisher);
          }
        </script>

app/views/chats/show.html.erb
 <div id="myPublisherDiv"></div>
        <script type="text/javascript">
          // Initialize API key, session, and token...
          // Think of a session as a room, and a token as the key to get in to the room
          // Sessions and tokens are generated on your server and passed down to the client
          var apiKey = "44745342";
          var sessionId = <%= @chat.sessionId %>;
          var token = <%= @chat.token %>;

          // Initialize session, set up event listeners, and connect
          var session = TB.initSession(sessionId);
          session.addEventListener('sessionConnected', sessionConnectedHandler);
          session.connect(apiKey, token);
          
          function sessionConnectedHandler(event) {
            var publisher = TB.initPublisher(apiKey, 'myPublisherDiv');
            session.publish(publisher);
          }
        </script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Homebase</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <script src='https://swww.tokbox.com/webrtc/v2.0/js/TB.min.js'></script>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>